### ISSUE TITLE
runProdWebpack Gradle task in the branch rs-new-design

### ISSUE THREAD

**Issue by leonardol** [researchspace/researchspace#355]
When running the Gradle task `runProdWebpack` in the branch `rs-new-design` an issue occurs:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prod'
1 verbose cli ]
2 info using npm@6.14.16
3 info using node@v12.22.12
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle @~preprod: @
6 info lifecycle @~prod: @
7 verbose lifecycle @~prod: unsafe-perm in lifecycle true
8 verbose lifecycle @~prod: PATH: ...
9 verbose lifecycle @~prod: CWD: C:\Users\<username>\researchspace
10 silly lifecycle @~prod: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'webpack --bail --mode production --config webpack/webpack.prod.config.js'
10 silly lifecycle ]
11 silly lifecycle @~prod: Returned: code: 2  signal: null
12 info lifecycle @~prod: Failed to exec prod script
13 verbose stack Error: @ prod: `webpack --bail --mode production --config webpack/webpack.prod.config.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid @
15 verbose cwd C:\Users\<username>\researchspace
16 verbose Windows_NT 10.0.22631
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prod"
18 verbose node v12.22.12
19 verbose npm  v6.14.16
20 error code ELIFECYCLE
21 error errno 2
22 error @ prod: `webpack --bail --mode production --config webpack/webpack.prod.config.js`
22 error Exit status 2
23 error Failed at the @ prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```
```
10:59:04: Executing 'runProdWebpack'...

> Task :npmInstallCi

> core-js-pure@3.38.1 postinstall C:\Users\<username>\researchspace\node_modules\core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

added 1895 packages in 70.19s

> Task :runProdWebpack FAILED

> @ prod C:\Users\<username>\researchspace
> webpack --bail --mode production --config webpack/webpack.prod.config.js


Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings
2 actionable tasks: 2 executed
[webpack-cli] C:\Users\<username>\researchspace\node_modules\cosmiconfig\dist\index.js:78
    if (metaConfig.config?.loaders) {
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\<username>\researchspace\node_modules\fork-ts-checker-webpack-plugin\lib\plugin.js:27:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ prod: `webpack --bail --mode production --config webpack/webpack.prod.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<username>\AppData\Roaming\npm-cache\_logs\2024-09-11T09_00_22_191Z-debug.log

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runProdWebpack'.
> Process 'command 'npm.cmd'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 16s
11:00:22: Execution finished 'runProdWebpack'.
```

is there away to solve this?

**Comment by dianat** [comment]
@leonardol did you remove the node_modules folder before re-running ```./gradlew runAll ``` ?

**Comment by leonardol** [comment]
@dianat after removing the node_modules folder, the mentioned issue does not occur anymore.
