### ISSUE TITLE
git storage is buggy

### ISSUE THREAD

**Issue by lklic** [researchspace/researchspace#77]
We have had a bit of a rough ride with the Git storage and I wanted to share our experience with the community in case you are experiencing similar issues: 

We used git for our runtime storage for about 4 months, and it would break every few weeks. The result would be that if you tried to modify a template or anything that would write to the storage, you would not see any error and the change would not get saved. The logs display the following:
```
2020-04-12 17:44:19,919 DEBUG [git-storage-0] com.metaphacts.services.storage.git.GitStorage - Pushing changes to remote repository...
2020-04-12 17:44:21,379 DEBUG [git-storage-0] com.metaphacts.services.storage.git.GitStorage - Remote repository has other changes; trying to pull them and commit again
2020-04-12 17:44:21,380 DEBUG [git-storage-0] com.metaphacts.services.storage.git.GitStorage - Performing rollback to AnyObjectId[50f58b216ecdd18eeeb5be98b342c3af96801324]
2020-04-12 17:44:22,535 DEBUG [git-storage-0] com.metaphacts.services.storage.git.GitStorage - Pushing changes to remote repository...
2020-04-12 17:44:23,964 DEBUG [git-storage-0] com.metaphacts.services.storage.git.GitStorage - Remote repository has other changes; trying to pull them and commit again
2020-04-12 17:44:23,965 DEBUG [git-storage-0] com.metaphacts.services.storage.git.GitStorage - Performing rollback to AnyObjectId[50f58b216ecdd18eeeb5be98b342c3af96801324]
2020-04-12 17:44:25,151 DEBUG [git-storage-0] com.metaphacts.services.storage.git.GitStorage - Pushing changes to remote repository...
2020-04-12 17:44:26,538 DEBUG [git-storage-0] com.metaphacts.services.storage.git.GitStorage - Remote repository has other changes; trying to pull them and commit again
2020-04-12 17:44:26,538 DEBUG [git-storage-0] com.metaphacts.services.storage.git.GitStorage - Performing rollback to AnyObjectId[50f58b216ecdd18eeeb5be98b342c3af96801324]
2020-04-12 17:44:27,676 WARN [git-storage-0] com.metaphacts.services.storage.git.GitStorage - Failed to push changes to remote in background thread: Failed to push committed changes after 3 failed attempts
2020-04-12 17:44:27,677 DEBUG [git-storage-0] com.metaphacts.services.storage.git.GitStorage - Details:
com.metaphacts.services.storage.api.StorageException: Failed to push committed changes after 3 failed attempts
	at com.metaphacts.services.storage.git.GitStorage.pushChanges(GitStorage.java:591) ~[metaphacts-platform.jar:?]
	at com.metaphacts.services.storage.git.GitStorage.lambda$pushChangesAsynch$5(GitStorage.java:552) ~[metaphacts-platform.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
Trying to git pull or push manually did not resolve the issue, and I always had to re-clone the repository from the repo and start over.

The last time it happened was during modifying a field definition, and since those are written to the graph and storage as well, the change was made to the graph but not to storage. At the system startup there is a check to make sure those field definitions are in sync and it will throw an error if there is a field definition in the assets repository but not in storage, so it would not start. At that point I had to start over and switched back to nonVersionedStorage 

I created a support ticket with Metaphacts and they were aware of the issue, and though it may have had to do with fields and interaction with JGIT.

**Comment by aindlq** [comment]
Yes, we also find it extremely problematic. I believe that the error happens mainly because of some issue with LDP persistence. So currently in our deployments we using git storage only for templates, and disable LDP storage persistence by default in global.prop file:
```
repositoriesLDPLoad=,
repositoriesLDPSave=,
```

**Comment by lklic** [comment]
That is exactly what we did as well to temporarily allow the platform to start.

Any idea what was the reasoning behind backing up LDP containers to storage as well? It seems nice but a lot of overhead to maintain.

**Comment by lklic** [comment]
stale issue
